# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-20.04', 'macos-latest']
        #os: ['windows-latest']
        py: ['main']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install onnxruntime
        # pip install onnxruntime-gpu
        pip install https://github.com/htylab/tigerbx/archive/main.zip
        pip install -r requirements.txt
    - name: Run Pyinstaller 1
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller -p . -F --icon=./icons/icon.ico --add-data "./FreeSurferColorLUT.txt;./" --add-data "./icons/*;icons" ./${{ matrix.py }}.py
    - name: Run Pyinstaller 2
      if: matrix.os == 'ubuntu-20.04'
      run: |
        pyinstaller -p . -F --icon=./icons/icon.ico --add-data ./FreeSurferColorLUT.txt:./ --add-data ./icons/*:icons ./${{ matrix.py }}.py
    - name: Run Pyinstaller 3
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller -p . -F --icon=./icons/icon.ico --add-data ./FreeSurferColorLUT.txt:./ --add-data ./icons/*:icons ./${{ matrix.py }}.py
