# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install onnxruntime
        # pip install onnxruntime-gpu
        pip install https://github.com/htylab/tigerbx/archive/refs/tags/v0.1.15.tar.gz
        pip install -r requirements.txt

    - name: Install libegl1
      if: matrix.os == 'ubuntu-latest'
      run: |
        apt update
        apt install libegl1

    - name: Run Pyinstaller
      run: |
        pyinstaller tigerbxGUI.spec
        dist/tigerbxGUI --version

    - uses: actions/upload-artifact@v4
      with:
        name: TigerBX-gui-${{ matrix.os }}
        path: dist/*
